config/routes.rb
Authuser::Application.routes.draw do

  ActiveAdmin.routes(self)

  root :to => "home#index"
  match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}

  resources :profiles, :only => [:dashboard]

  resources :posts

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    if user.role? :admin
      can :manage, :all
    elsif user.role? :registered
      can :manage, Post do |post|
        post.user == user
      end
    elsif user.role? :staff
      can :manage, Post
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

  validates :title, :content , :presence => true
  #NOTE Return the recently published visible post ordered by their publish date
  scope :recent, limit(10).order("created_at ASC")
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  #NOTE cas_authenticatable provides single sign-on support for Devise applications. It acts as a replacement for database_authenticatable.
  #It builds on rubycas-client and should support just about any conformant CAS server
  devise :cas_authenticatable
  before_create :setup_username
  before_save :setup_role

  has_and_belongs_to_many :roles
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role_ids

  #TODO need to add role as an extra attribute which need to send by rubyCAS server in params[:cas_session]
  #NOTE cas_extra_attributes extracte the extra attribute and save data VirtualUser, which maint
  def cas_extra_attributes=(extra_attributes)
    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@#{extra_attributes.inspect}"
    extra_attributes.each do |name, value|
      case name.to_sym
        when :fullname
          self.fullname = value
        when :email
          self.email = value
      end
    end
  end

  def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  end

  private
  # Default role is "staff"
  def setup_role 
    if self.role_ids.empty?     
      self.role_ids = [2] 
    end
  end

  #TODO Need to remove this callback and make email as authenticate
  # Setting up username as devise need username column to authenticate
  def setup_username
    self.username = self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # Mandatory authentication
#  def authenticate_user!
#    CASClient::Frameworks::Rails::Filter.filter(self)
#  end
#
## Optional authentication (not in Devise)
#  def authenticate_user
#    CASClient::Frameworks::Rails::GatewayFilter
#  end
#
#  def user_signed_in?
#    session[:cas_user].present?
#  end

  #def after_sign_in_path_for(resource)
  #  resource.roles == 'admin' ? admin_dashboard_path : user_path(resource)
  #end
  #
  #def authenticate_admin_user!
  #  raise SecurityError unless current_user.try(:role) == 'admin'
  #end

  def check_admin_role
    return if current_user.role?(:admin)
    flash[:notice] = "You need to be an admin to access this part of the application"
    redirect_to root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def has_role?(current_user, role)
    return !!current_user.roles.find_by_name(role.to_s.camelize)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    @user = User.find(current_user.id)
    if @user.role? :admin
      redirect_to admin_dashboard_path, :notice => "Aloah Admin!"
    else
      respond_to do |format|
        format.html # dashboard.html.erb
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # To access a Devise form from a non-Devise controller for that added devise_mapping method
  # to map the model name
  def devise_mapping
    Devise.mappings[:user]
  end

  # To access a Devise form from a non-Devise controller for that added resource_name method
  # to map the resource type going to used
  def resource_name
    devise_mapping.name
  end

  # To access a Devise form from a non-Devise controller for that added resource_class
  def resource_class
    devise_mapping.to
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/users/_form.html.erb
<%= semantic_form_for [:admin, @user] do |f| -%>
    <fieldset class="inputs"><legend><span>Post Details</span></legend>
      <ol>
        <li class="text input optional">
          <%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => 'control-label' %>
          <%= f.text_field :email %>
        </li>
        <li class="text input optional">
          <%= f.label :password, t("activerecord.attributes.user.password", :default => "password"), :class => 'control-label' %>
          <%= f.password_field :password, :class => 'password_field' %>
        </li>
        <li class="text input optional">
          <%= f.label :Password, t("activerecord.attributes.user.password_confirmation", :default => "password_confirmation"), :class => 'control-label' %>
          <%= f.password_field :password_confirmation, :class => 'password_field' %></br>
        </li>
        <% for role in Role.find(:all) %>
            <li class="text checkbox optional">
              <%= f.label role.name , :class => 'control-label' %>
              <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
            </li>
        <% end %>
      </ol>
    </fieldset>
    <fieldset class="actions">
      <ol>
        <li class="action input_action " id="post_submit_action">
          <input name="commit" type="submit" value="Create User">
        </li>
        <li class="cancel">
          <%= link_to "Cancel", admin_dashboard_path %>
        </li>
      </ol>
    </fieldset>
<% end -%>

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user], :url => admin_user_path(@user), :html => { :class => "form-horizontal", :id => "edit_user" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| -%>
   <tr>
    <td><%= user.id %></td>
        <td><%= link_to user.email, admin_user_path(user) %>
    </td>
        <td><%= user.created_at %></td>
    <td>
      <%= link_to "Show", admin_user_path(user) %>
      <%= link_to "Edit", edit_admin_user_path(user) %>
      <%= link_to "Destroy", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_admin_user_path, :class => 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user], :url => admin_users_path, :html => { :class => "form-horizontal"} do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/show.html.erb
<label class="label"><%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</label>
<p><%= @user.email %></p>

<div class="form-actions">
<%= link_to "Back", admin_users_path, :class => 'btn'  %>
<%= link_to "Edit", edit_admin_user_path(@user), :class => 'btn' %>
<%= link_to "Delete", admin_user_path(@user), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/home/index.html.erb
<div class="hero-unit">
  <h2>User Management and account Management!</h2>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Authuser" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Authuser</a>
      <div class="container nav-collapse">
        <ul class="nav">
          <% if user_signed_in? %>
              <li class="nav"><%= link_to "My Profile", user_root_path%></li>
              <li class="nav"><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
          <%else%>
              <li><%= link_to('Login', new_user_session_path) %></li>
              <li><%#= link_to('Register', new_user_registration_path) %></li>
          <%end%>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
      <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>

      <div class="span9">
        <%= yield %>
      </div>
      <div class="span3">
        <div class="well sidebar-nav">
          <h3>Sidebar</h3>
          <ul class="nav nav-list">
            <li class="nav-header">Sidebar</li>

          </ul>
        </div><!--/.well -->
      </div><!--/span-->
    </div><!--/row-->
  </div><!--/content-->

</div> <!-- /container -->

<footer class="modal-footer ftr">
  <p>&copy; Company 2012</p>
</footer>

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Authuser" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Authuser</a>
      <div class="container nav-collapse">
        <ul class="nav">
          <% if user_signed_in? %>
              <li class="nav"><%= link_to "My Profile", user_root_path%></li>
              <li class="nav"><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
          <%else%>
              <li><%= link_to('Login', new_user_session_path) %></li>
              <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
                  <li><%= link_to "Forgot your password?", new_password_path(resource_name) %></li>
              <% end -%>
              <li><%#= link_to('Register', new_user_registration_path) %></li>
          <%end%>
          <li><%= link_to "Post", posts_path%></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
      <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>

      <div class="span9">
        <%= yield %>
      </div>
      <!--<div class="span3">-->
        <!--<div class="well sidebar-nav">-->
          <!--<h3>Sidebar</h3>-->
          <!--<ul class="nav nav-list">-->
            <!--<li class="nav-header">Sidebar</li>-->

          <!--</ul>-->
        <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
      <!--</div>&lt;!&ndash;/span&ndash;&gt;-->
    </div><!--/row-->
  </div><!--/content-->

</div> <!-- /container -->

<footer class="modal-footer ftr">
  <p>&copy; Company 2012</p>
</footer>

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post ,:html => { :class => "form-horizontal"}  do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <label class="control-label">Title</label>
      <div class="controls">
        <%= f.text_field :title %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Content</label>
      <div class="controls">
        <%= f.text_area :content ,:rows=>"3"%>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit "Create Post",:class => "btn btn-primary" %>

<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="span4">
    <h1>Editing post</h1>
  </div>
  </div>
<div class="row">
  <%= render 'form' %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="row show-grid">
  <div class="span4">
    <h1>Listing posts</h1>
  </div>
  <div class="span3 offset2">
    <%= link_to 'New Post', new_post_path ,:class => "btn btn-primary" %>
  </div>
</div>

  <table class="table table-bordered">
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Actions</th>

    </tr>

    <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.content %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
    <% end %>
  </table>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="span4">
    <h1>Show Post</h1>
  </div>
  <div class="span8">
    <dl>
      <dt>Title</dt>
      <dd>
        <%= @post.title %>
      </dd>
      <dt>Content</dt>
      <dd>
        <%= @post.content %>
      </dd>
    </dl>
  </div>
</div>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/dashboard.html.erb
<div xmlns="http://www.w3.org/1999/html">
  <p>Welcome, <h5><%= @user.email %></h5></br>
    Here you can <%#= link_to "Edit your profile", edit_user_registration_path(current_user), :class => "custom-link" %></p>
</div>